INSERT INTO
  kpler_trade_computed (
    trade_id,
    flow_id,
    product_id,
    pricing_scenario,
    eur_per_tonne,
    pricing_commodity,
    kpler_product_commodity_id,
    ship_insurer_names,
    ship_insurer_iso2s,
    ship_insurer_regions,
    ship_owner_names,
    ship_owner_iso2s,
    ship_owner_regions,
    ownership_sanction_coverage,
    ship_flag_iso2s,
    flag_sanction_coverage,
    step_zone_names,
    step_zone_iso2s,
    step_zone_regions,
    step_zone_ids,
    vessel_ages,
    avg_vessel_age,
    largest_vessel_type,
    largest_vessel_capacity_cm,
    crea_designations
  )
SELECT
  trade_id,
  flow_id,
  product_id,
  pricing_scenario,
  eur_per_tonne,
  pricing_commodity,
  kpler_product_commodity_id,
  ship_insurer_names,
  ship_insurer_iso2s,
  ship_insurer_regions,
  ship_owner_names,
  ship_owner_iso2s,
  ship_owner_regions,
  ownership_sanction_coverage,
  ship_flag_iso2s,
  flag_sanction_coverage,
  step_zone_names,
  step_zone_iso2s,
  step_zone_regions,
  step_zone_ids,
  vessel_ages,
  avg_vessel_age,
  largest_vessel_type,
  largest_vessel_capacity_cm,
  crea_designations
FROM
  ktc_kpler_trade_computed;

INSERT INTO
  kpler_trade_computed_ships (
    trade_id,
    flow_id,
    product_id,
    vessel_imo,
    pricing_scenario,
    ownership_sanction_coverage,
    pricing_commodity,
    kpler_product_commodity_id,
    flag_sanction_coverage,
    ship_insurer_name,
    ship_insurer_iso2,
    ship_insurer_region,
    ship_owner_name,
    ship_owner_iso2,
    ship_owner_region,
    vessel_age,
    ship_flag_iso2,
    eur_per_tonne,
    crea_designation,
    step_in_trade,
    total_steps_in_trade
  )
SELECT
  trade_id,
  flow_id,
  product_id,
  vessel_imo,
  pricing_scenario,
  ownership_sanction_coverage,
  pricing_commodity,
  kpler_product_commodity_id,
  flag_sanction_coverage,
  ship_insurer_name,
  ship_insurer_iso2,
  ship_insurer_region,
  ship_owner_name,
  ship_owner_iso2,
  ship_owner_region,
  vessel_age,
  ship_flag_iso2,
  eur_per_tonne,
  crea_designation,
  step_in_trade,
  total_steps_in_trade
FROM
  ktc_kpler_trade_computed_ships;

ANALYZE kpler_trade_computed;

ANALYZE kpler_trade_computed_ships;
