steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine:latest || exit 0",
      ]

  - name: "gcr.io/cloud-builders/docker"
    script: |
      docker buildx build \
        -t europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine:${COMMIT_SHA} \
        -f Dockerfile.engine \
        --cache-from europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine:latest \
        .
    automapSubstitutions: true
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine:${COMMIT_SHA}"
