# We separate the engine dependencies stage from the engine stage to be able to
# cache the dependency stage.
steps:
  # First, pull the existing images to use as the cache.
  - name: "gcr.io/cloud-builders/docker"
    script: |
      docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine:latest || exit 0
      docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine-dependencies:latest || exit 0

  # Next, build the engine dependencies stage and then the engine stage. We
  # don't use the
  - name: "gcr.io/cloud-builders/docker"
    script: |
      docker buildx build \
        -t europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine-dependencies:latest \
        -f Dockerfile.engine \
        --cache-from europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine-dependencies:latest \
        --target dependencies \
        .

      docker buildx build \
        -t europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine:${COMMIT_SHA} \
        -f Dockerfile.engine \
        --cache-from europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine:latest \
        .
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine:${COMMIT_SHA}"
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/tracker/engine-dependencies:latest"
options:
  automapSubstitutions: true
