name: russia-engine
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.4.2
  - gdal=3.5
  - psycopg2=2.9
  - Flask=2.0
  - flask-restful=0.3
  - flask-restx=0.5
  - flask-cors=3.0.10
  - grpcio
  - sqlalchemy=1.4.34
  - geoalchemy2
  - rasterio
  - numpy
  - pytest=7.0
  - proj
  - flask-restx
  - beautifulsoup4
  - requests
  - selenium
  - pygeos
  - google-cloud-storage
  - google-cloud-secret-manager=1.0.0
  - Unidecode
  - matplotlib
  - seaborn
  - scikit-image
  - geopandas
  - shapely
  - tqdm
  - python-decouple
  - pre-commit
  - Werkzeug=2.0.3
  - country_converter
  - pip
  - pip:
    - slack-logger
    - slack_sdk
    - forex-python==1.8
    - kpler.sdk==1.0.29
    - pymongo[srv]==4.0.2
    - flask_mail==0.9.1
    - webdriver_manager~=3.8.3
    - pyreadr==0.4.7
    - lxml
