service: default
runtime: python36
instance_class: F4_1G
env_variables:
  PROJECT_ID: 'fossil-shipment-tracker'
entrypoint: gunicorn -b :$PORT -w 2 app:app
automatic_scaling:
  min_instances: 1
inbound_services:
  - warmup
app_engine_apis: true
