name: russia-api
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.4.2
  - psycopg2=2.9
  - Flask=2.0
  - flask-restful=0.3
  - flask-restx=0.5
  - flask-cors=3.0.10
  - sqlalchemy=1.4.34
  - geoalchemy2
  - grpcio
  - numpy
  - pytest=7.0
  - proj
  - requests
  - google-cloud-storage
  - google-cloud-secret-manager=1.0.0
  - geopandas
  - shapely
  - tqdm
  - python-decouple
  - pre-commit
  - gunicorn
  - Werkzeug=2.0.3
  - protobuf=3.20
  - pip
  - pip:
    - slack-logger
    - slack_sdk
    - forex-python==1.8
    - kpler.sdk==1.0.29
    - pymongo[srv]==4.0.2
    - flask_mail==0.9.1
