name: API Workflow

on:
  push:
    branches:
      - "master"
    paths:
      - "api/**"
      - "base/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "${{ secrets.ENV_FILE }}" > ./api/.env

      - name: Run tests
        working-directory: ./api/
        run: python -m pytest -c ./tests/pytest.ini -v

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: |
      needs.test.result == 'success' &&
      (
        startsWith(github.event.head_commit.message, 'Release Api') ||
        github.event_name == 'workflow_dispatch'
      )

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: GCP Authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy 'api' to Google App Engine
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          deliverables: ./api/api_production.yaml
          project_id: "fossil-shipment-tracker"
          promote: true
          flags: "--stop-previous-version"
