# Deploy development
name: russia-api-deploy-development

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.8.2

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Setup Poetry ${{ env.POETRY_VERSION }}
      uses: Gr1N/setup-poetry@v9
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Setup Poetry export plugin
      working-directory: api
      run: |
        poetry self add poetry-plugin-export@1.8.0
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      working-directory: api
      run: |
        poetry export -f requirements.txt --without-hashes --without-urls \
          | sed \
            -e '/^base @/ d' \
            -e '/^-e file/ d' \
          > requirements.txt

        pip install -r requirements.txt
        cp -r ../base/base base

        echo "Contents of requirements.txt is:"
        cat requirements.txt
        echo "---"
    - name: Authenticate
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v1
      with:
        project_id: ${{ vars.PROJECT_ID }}
        deliverables: ./api/api_development.yaml
        promote: true
        flags: '--stop-previous-version'
