# Deploy production
name: russia-api-deploy-production

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.8.2


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Setup Poetry ${{ env.POETRY_VERSION }}
      uses: Gr1N/setup-poetry@v9
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Install dependencies
      run: |
        poetry export -f requirements.txt --output api/requirements.txt
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
    - name: Authenticate
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v1
      with:
        deliverables: ./api/api_production.yaml
        promote: true
        flags: '--stop-previous-version'
