# Run our tests for engine
name: russia-engine-test

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.8.2

    steps:
    - name: Checkout pull request branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Setup Poetry ${{ env.POETRY_VERSION }}
      uses: Gr1N/setup-poetry@v9
      with:
        poetry-version: ${{ env.POETRY_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        poetry export -f requirements.txt --output requirements.txt
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        PROJECT_ID: ${{ vars.PROJECT_ID }}
        ENVIRONMENT: ${{ vars.ENVIRONMENT }}

        DB_URL_PRODUCTION: ${{ secrets.DB_URL_PRODUCTION }}

        PGHOST_PRODUCTION: ${{ secrets.PGHOST_PRODUCTION }}
        PGPORT_PRODUCTION: ${{ secrets.PGPORT_PRODUCTION }}
        PGUSER_PRODUCTION: ${{ secrets.PGUSER_PRODUCTION }}
        PGPASSWORD_PRODUCTION: ${{ secrets.PGPASSWORD_PRODUCTION }}

        KEY_MARINETRAFFIC_EV01: ${{ secrets.KEY_MARINETRAFFIC_EV01 }}
        KEY_MARINETRAFFIC_VI01: ${{ secrets.KEY_MARINETRAFFIC_VI01 }}
        KEY_MARINETRAFFIC_VD02: ${{ secrets.KEY_MARINETRAFFIC_VD02 }}
        KEY_MARINETRAFFIC_EV02: ${{ secrets.KEY_MARINETRAFFIC_EV02 }}
        KEY_MARINETRAFFIC_PS01: ${{ secrets.KEY_MARINETRAFFIC_PS01 }}
        KEY_MARINETRAFFIC_EV01_CALL_BASED: ${{ secrets.KEY_MARINETRAFFIC_EV01_CALL_BASED }}

        KEY_DATALASTIC: ${{ secrets.KEY_DATALASTIC }}

        EQUASIS_PASSWORD: ${{ secrets.EQUASIS_PASSWORD }}
        EQUASIS_ACCOUNT_RANGE_START: ${{ vars.EQUASIS_ACCOUNT_RANGE_START }}
        EQUASIS_ACCOUNT_RANGE_END: ${{ vars.EQUASIS_ACCOUNT_RANGE_END }}

      run: |
        pytest -c ./engine/tests/pytest.ini -v
