# Deploy production
name: russia-engine-deploy-production

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.8.2

    steps:
    - uses: actions/checkout@v3
    - name: Authenticate
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Build and deploy latest docker image
      id: build-and-deploy-image
      run: 'gcloud builds submit --region=europe-west1 --config cloudbuild-engine.yaml'
    - name: Deploy latest job specs
      id: deploy-job-spec
      run: |
        gcloud run jobs replace infra/jobs/engine.yaml
        gcloud run jobs replace infra/jobs/engine-big.yaml
