# Run our tests for api
name: russia-api-test

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      POETRY_VERSION: 1.8.2

    steps:
    - name: Checkout pull request branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Setup Poetry ${{ env.POETRY_VERSION }}
      uses: Gr1N/setup-poetry@v9
      with:
        poetry-version: ${{ env.POETRY_VERSION }}

    - name: Install dependencies
      run: poetry install
      working-directory: ./api/

    - name: Test with pytest
      working-directory: ./api/
      env:
        PROJECT_ID: ${{ vars.PROJECT_ID }}
        ENVIRONMENT: ${{ vars.ENVIRONMENT }}
        API_KEY: ${{ secrets.API_KEY }}

        DB_URL_PRODUCTION: ${{ secrets.DB_URL_PRODUCTION }}

        PGHOST_PRODUCTION: ${{ secrets.PGHOST_PRODUCTION }}
        PGPORT_PRODUCTION: ${{ secrets.PGPORT_PRODUCTION }}
        PGUSER_PRODUCTION: ${{ secrets.PGUSER_PRODUCTION }}
        PGPASSWORD_PRODUCTION: ${{ secrets.PGPASSWORD_PRODUCTION }}
      run: |
        poetry run pytest -c ./tests/pytest.ini -v
